name: antsoup
description: "A antsoup project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # 상태관리
  get: ^4.7.2

  # 네트워킹
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  http: ^1.5.0
  html: ^0.15.6

  # UI 컴포넌트
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # 차트 및 그래프
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.11

  # 로컬 저장소
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 로컬 알림만 유지
  flutter_local_notifications: ^17.0.0

  # 유틸리티
  intl: ^0.19.0
  logger: ^2.4.0
  permission_handler: ^11.3.1
  word_cloud: ^1.0.3

  # 아이콘
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # 코드 생성
  build_runner: ^2.4.12
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800